import Head from 'next/head';
import styles from '@/styles/Dogs.module.css';

export default function Dogs() {
  return (
    <>
      <Head>
        <title>Fetch Dogs</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main className={styles.main}>
        <h1>Dogs</h1>
        <div className={styles.search}>
          <label htmlFor='dog-search'>Search:</label>
          <input type='search' id='dog-search' placeholder='' />
        </div>
      </main>
    </>
  );
}
