import Head from 'next/head';
import Router from 'next/router';
import { useState, useEffect } from 'react';
import useSWR from 'swr';
import styles from '@/styles/Dogs.module.css';

interface Dog {
  id: string;
  img: string;
  name: string;
  age: number;
  zip_code: string;
  breed: string;
}

const URL = 'https://frontend-take-home-service.fetch.com';
const fetcher = async (url: string) => {
  let response = await fetch(url, { credentials: 'include' });
  return await response.json();
};

export default function Dogs() {
  const { data, error } = useSWR(`${URL}/dogs/search?sort=breed:asc`, fetcher);
  const [dogIds, setDogIds] = useState([]);
  const [dogs, setDogs] = useState([]);

  useEffect(() => {
    if (!error && data) setDogIds(data.resultIds);
  }, []);

  function fetchDogs() {
    fetch('https://frontend-take-home-service.fetch.com/dogs', {
      method: 'POST',
      credentials: 'include',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(dogIds),
    })
      .then((response) => response.json())
      .then((data) => setDogs(data));
  }

  useEffect(() => {
    fetchDogs();
  }, []);

  return (
    <>
      <Head>
        <title>Fetch Dogs</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main className={styles.main}>
        <h1>Dogs</h1>
        <div className={styles.dogs}>
          <ol>
            {dogs.map((dog: Dog, index: number) => (
              <li key={index}>
                <img
                  src={dog.img}
                  alt={`${dog.name}, a ${dog.age} year old ${dog.breed}.`}
                />
                <div className={styles.overlay}>
                  <p className={styles.name}>{dog.name}</p>
                  <p className={styles.breed}>{dog.breed}</p>
                  <p className={styles.age}>{`${dog.age} year${
                    dog.age !== 1 ? 's' : ''
                  } old`}</p>
                </div>
              </li>
            ))}
          </ol>
        </div>
      </main>
    </>
  );
}
