import Head from 'next/head';
import Router, { useRouter } from 'next/router';
import { useState } from 'react';
import styles from '@/styles/Home.module.css';

export default function Home() {
  const router = useRouter();
  const { expired } = router.query;
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [loginError, setLoginError] = useState(false);

  async function handleSubmit() {
    try {
      const response = await fetch(
        'https://frontend-take-home-service.fetch.com/auth/login',
        {
          method: 'POST',
          credentials: 'include',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            name: name,
            email: email,
          }),
        }
      );

      if (response.ok) {
        Router.push('/dogs');
      }
    } catch (error) {
      setLoginError(true);
    }
  }

  return (
    <>
      <Head>
        <title>Fetch Dogs</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main className={styles.main}>
        <h1>Login</h1>
        {(loginError && (
          <p className={styles.error}>Login failed, please try again.</p>
        )) ||
          (expired && (
            <p className={styles.error}>
              Session expired, please log in again.
            </p>
          ))}
        <form
          className={styles.login}
          onSubmit={(event) => {
            event.preventDefault();
            handleSubmit();
          }}>
          <label htmlFor='name'>Name</label>
          <input
            type='text'
            id='name'
            name='name'
            placeholder='John Wick'
            required
            onChange={(event) => setName(event.target.value)}
          />
          <label htmlFor='email'>Email</label>
          <input
            type='email'
            id='email'
            name='email'
            placeholder='johnwick@gmail.com'
            required
            onChange={(event) => setEmail(event.target.value)}
          />
          <button type='submit' className={styles.submit}>
            Login
          </button>
        </form>
      </main>
    </>
  );
}
