import Head from 'next/head';
import Router, { useRouter } from 'next/router';
import { useState } from 'react';
import styles from '@/styles/Home.module.css';

export default function Home() {
  const router = useRouter();
  const { error, expired } = router.query;

  return (
    <>
      <Head>
        <title>Fetch Dogs</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main className={styles.main}>
        <h1>Login</h1>
        {(error && (
          <p className={styles.error}>Login failed, please try again.</p>
        )) ||
          (expired && (
            <p className={styles.error}>
              Session expired, please log in again.
            </p>
          ))}
        <form className={styles.login} action='/api/login'>
          <label htmlFor='name'>Name</label>
          <input
            type='text'
            id='name'
            name='name'
            placeholder='John Wick'
            required
          />
          <label htmlFor='email'>Email</label>
          <input
            type='email'
            id='email'
            name='email'
            placeholder='johnwick@gmail.com'
            required
          />
          <button type='submit' className={styles.submit}>
            Login
          </button>
        </form>
      </main>
    </>
  );
}
